# See the following example config file for more options:
# https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml

global:

route:
  group_by: ['alertname', 'cluster', 'service']

  # Delay initial notification to collect other notifications in the same group
  group_wait: 15s

  # How long to wait before sending another notification for the same group
  group_interval: 30s

  # How long to wait before resending a successfully-sent notification
  repeat_interval: 2h

  # A default receiver, if none of the below routes match
  receiver: dev-hipchat

  routes:
  - match:
      severity: critical
    receiver: dev-pager

receivers:
- name: 'dev-pager'
  pagerduty_configs:
  - service_key: insert-pagerduty-key-here

- name: 'dev-hipchat'
  hipchat_configs:
  - api_url: https://api.hipchat.com # Can change this to 'https://your-organization.hipchat.com'
    message: >
      [{{ if eq .Status "firing" }}FIRING{{ else }}RESOLVED{{ end }}]
      {{ .CommonAnnotations.description }}
    send_resolved: true
    room_id: '123456'
    auth_token: abcdefABCDEF123456789

