version: "3"

services:
  example-app:
    image: prometheus-alertmanager-example-app<localBuild>
    ports:
      - "9999:9999"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/opt/prometheus
    command: [
      "-config.file", "/opt/prometheus/prometheus.yml",
      "-alertmanager.url", "http://alertmanager:9093"
    ]

  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager:/opt/alertmanager
    command: [
      "-config.file", "/opt/alertmanager/alertmanager.yml"
    ]


