global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Rate at which alerting rules are evaluated.
  # Low value for demo purposes. Default is 1m.
  # https://pracucci.com/prometheus-understanding-the-delays-on-alerting.html
  evaluation_interval: 1s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'example-monitor'

rule_files:
  - '/opt/prometheus/alerting.rules'

scrape_configs:
  - job_name: 'example-job'

    # Rate at which Prometheus scrapes the above target.
    # Would be higher in real usage.
    scrape_interval: 1s

    static_configs:
      - targets:
        - 'example-app:9999'

